version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./askbot.db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./askbot.db:/app/askbot.db
      - ./charts:/app/charts
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./charts:/usr/share/nginx/html/charts:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  redis_data: 